{% set name = "python-on-whales" %}
{% set version = "0.64.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-on-whales-{{ version }}.tar.gz
  sha256: eb6f55bb529fc287dc6fea693cd35cc702913a61f3e1f051efc162f720f3c154

build:
  entry_points:
    - python-on-whales=python_on_whales.command_line_entrypoint:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.7,<4.0
    - pip
  run:
    - python >=3.7,<4.0
    - pydantic >=1.5,<3,!=2.0.*
    - requests
    - tqdm
    - typer >=0.4.1
    - typing-extensions

test:
  imports:
    - python_on_whales
  commands:
    - pip check
    - python-on-whales --help
  requires:
    - pip

about:
  home: https://pypi.org/project/python-on-whales/
  summary: A Docker client for Python, designed to be fun and intuitive!
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrispyles
    - yuvipanda
