{% set name = "python-on-whales" %}
{% set version = "0.77.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: fc5f45c7cab9d545a6a47abe9e0fb70b26f852c18c777f308f646f84fb7dce78

build:
  entry_points:
    - python-on-whales=python_on_whales.command_line_entrypoint:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }},<4.0
    - pydantic >=1.9,<3,!=2.0.*
    - requests
    - tqdm
    - typer >=0.4.1
    - typing-extensions

test:
  imports:
    - python_on_whales
  commands:
    - pip check
    - python-on-whales --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/python-on-whales/
  summary: A Docker client for Python, designed to be fun and intuitive!
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrispyles
    - yuvipanda
